new ubuntu options

diff --git a/update_ami b/update_ami
--- a/update_ami
+++ b/update_ami
@@ -1,29 +1,31 @@
 #!/bin/bash
 [ ${UID} -ne 0 ] && echo "be you root?" && exit
-
+WORKDIR=$1;
 BASEDIR=$(cd $(dirname $0);pwd)
+
+[ -z ${WORKDIR} ] && echo "workdir?" && exit 1;
+[ ! -d ${WORKDIR} ] && echo "full path to workdir" && exit 1;
+
 . ${BASEDIR}/dependencies
-. ${BASEDIR}/credentials
+. ${BASEDIR}/credentials ${WORKDIR}
 . ${BASEDIR}/ec2-setup
 
-[ -z ${IMAGE} ] && IMAGE=/opt/amazon/ubuntu.fs
+[ -z ${IMAGE} ] && echo "image?" && exit
 [ -z ${DIST} ] && DIST=lucid
-
-IMDIR=$(dirname ${IMAGE})
 ######################################################################
 # Bundle the image for shipping to S3
 #
 ami_cmd ec2-bundle-image -d ${IMDIR} -i ${IMAGE} --arch i386
-[ ! -f ${IMAGE}.manifest.xml ] && echo "${IMAGE}.manifest.xml failed to build" && exit 1;
+[ ! -f ${IMAGE}.manifest.xml ] && echo "$(basename ${IMAGE}).manifest.xml failed to build" && exit 1;
 #
 ######################################################################
 
 ######################################################################
 # Ship the image to S3
 # http://docs.amazonwebservices.com/AmazonS3/2006-03-01/index.html?BucketRestrictions.html
-BUCKET="ubuntu-${DIST}-$(md5sum ${IMAGE}|awk '{print $1}')"
+BUCKET="websages-ubuntu-${DIST}-$(md5sum ${IMAGE}|awk '{print $1}')"
 echo "Shipping ${BUCKET} to S3..."
-ami_cmd ec2-upload-bundle -b websages-${BUCKET} -m ${IMAGE}.manifest.xml -a ${AWS_ACCESS} -s ${AWS_SECRET} 
+ami_cmd ec2-upload-bundle -b ${BUCKET} -m $(basename ${IMAGE}).manifest.xml -a ${AWS_ACCESS} -s ${AWS_SECRET} 
 #
 ######################################################################
 
@@ -32,9 +34,12 @@ ami_cmd ec2-upload-bundle -b websages-${BUCKET} -m ${IMAGE}.manifest.xml -a ${AW
 #
 AKI=aki-4c7d9525 # assumes partitioned with grub.conf on first partition ( pv-grub-hd00 )
 AKI=aki-407d9529 # assumes one big partition ( pv-grub-hd0 )
+
+# ami-7000f019 lucid that usees aki-v407d9529
+
 sleep 10         # we don't see the image for a bit...
 echo "Registering the image..."
-AMI=$(api_cmd ec2-register websages-${BUCKET}/ubuntu.fs.manifest.xml --kernel ${AKI}|awk '{print $2}')
+AMI=$(api_cmd ec2-register ${BUCKET}/$(basename ${IMAGE}).manifest.xml --kernel ${AKI}|awk '{print $2}')
 [ -z "${AMI}" ] && exit;
 #
 ######################################################################
@@ -48,7 +53,7 @@ INSTANCE=$(api_cmd ec2-run-instances ${AMI} -key eir --kernel ${AKI} --block-dev
 ######################################################################
 
 ######################################################################
-# Watch the console until it's output is greater thant 10 lines and it stops growing for 20 seconds
+# Watch the console until it's output is greater thant 10 lines and it stops growing for 30 seconds
 #
 if [ ! -z "${INSTANCE}" ];then
     export CONSOLE_OUTPUT=$(mktemp /tmp/ec2.console.XXXX)
@@ -56,7 +61,7 @@ if [ ! -z "${INSTANCE}" ];then
     while [ ${CONSOLE_OUTPUT_LENGTH} -lt 10 ]; do 
         clear; 
         api_cmd ec2-get-console-output ${INSTANCE} > ${CONSOLE_OUTPUT} 2>&1; 
-        sleep 20; 
+        sleep 30; 
         CONSOLE_OUTPUT_LENGTH=$(wc -l ${CONSOLE_OUTPUT}|awk '{print $1}'); 
     done
     export LAST_LENGTH=${CONSOLE_OUTPUT_LENGTH}
@@ -93,6 +98,6 @@ api_cmd ec2-deregister ${AMI}
 # Delete the bucket
 #
 echo "Deleting the bucket"
-ami_cmd ec2-delete-bundle -b websages-${BUCKET} -m ${IMAGE}.manifest.xml -a ${AWS_ACCESS} -s ${AWS_SECRET} --clear
+ami_cmd ec2-delete-bundle -b ${BUCKET} -m $(basename ${IMAGE}).manifest.xml -a ${AWS_ACCESS} -s ${AWS_SECRET} --clear
 #
 ######################################################################
